apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: trapp-demo
spec:
  storageClassName: ase-node-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
